walmart_project:
  outputs:
    dev:
      catalog: walmart_db_gautam
      host: dbc-e09dac1b-4ad5.cloud.databricks.com
      http_path: /sql/1.0/warehouses/411be12ab75a20c6
      schema: dbt_schema
      threads: 1
      token: "{{ env_var('DATABRICKS_TOKEN') }}"
      type: databricks
  target: dev
